package bsu.rpact.medionefrontend.utils;

import java.util.HashMap;
import java.util.Map;

public class CachedTranslatorUtils {

    public static Map<String, String> translations = new HashMap<>();

    static {
        translations.put("Pharmaceutical dose form (dose form)", "Фармацевтическая форма дозирования");
        translations.put("Chewable tablet", "Жевательная таблетка");
        translations.put("Conventional release oromucosal solution for mouthwash (dose form)", "Обычное растворное оромукозальное средство для полоскания рта");
        translations.put("Oral drops", "Капли для приема внутрь");
        translations.put("Oral drops solution", "Раствор капель для приема внутрь");
        translations.put("Oral drops suspension", "Суспензия капель для приема внутрь");
        translations.put("Oral drops emulsion", "Эмульсия капель для приема внутрь");
        translations.put("Oral solution", "Раствор для приема внутрь");
        translations.put("Oral suspension", "Суспензия для приема внутрь");
        translations.put("Oral emulsion", "Эмульсия для приема внутрь");
        translations.put("Powder for oral solution", "Порошок для приготовления раствора для приема внутрь");
        translations.put("Powder for oral suspension", "Порошок для приготовления суспензии для приема внутрь");
        translations.put("Granules for oral solution", "Гранулы для приготовления раствора для приема внутрь");
        translations.put("Granules for oral suspension", "Гранулы для приготовления суспензии для приема внутрь");
        translations.put("Conventional release oral syrup (dose form)", "Обычный растворный сироп для приема внутрь");
        translations.put("Powder for conventional release oral syrup (dose form)", "Порошок для обычного растворного сиропа для приема внутрь");
        translations.put("Granules for conventional release oral syrup (dose form)", "Гранулы для обычного растворного сиропа для приема внутрь");
        translations.put("Oral gel", "Гель для приема внутрь");
        translations.put("Oral paste", "Паста для приема внутрь");
        translations.put("Oral powder", "Порошок для приема внутрь");
        translations.put("Effervescent oral granules", "Шипучие гранулы для приема внутрь");
        translations.put("Gastro-resistant oral granules (dose form)", "Желудочнокишечнорастворимые гранулы для приема внутрь");
        translations.put("Prolonged-release oral granules (dose form)", "Гранулы с продолжительным высвобождением для приема внутрь");
        translations.put("Modified-release oral granules", "Модифицированные гранулы для приема внутрь");
        translations.put("Gastro-resistant oral capsule (dose form)", "Желудочнокишечнорастворимая капсула для приема внутрь");
        translations.put("Prolonged-release oral capsule", "Капсула с продолжительным высвобождением для приема внутрь");
        translations.put("Modified-release oral capsule", "Модифицированная капсула для приема внутрь");
        translations.put("Gastro-resistant oral tablet (dose form)", "Желудочнокишечнорастворимая таблетка для приема внутрь");
        translations.put("Prolonged-release oral tablet", "Таблетка с продолжительным высвобождением для приема внутрь");
        translations.put("Modified-release oral tablet (dose form)", "Модифицированная таблетка для приема внутрь");
        translations.put("Oral lyophilisate", "Лиофилизат для приема внутрь");
        translations.put("Oral gum", "Жевательная резинка для приема внутрь");
        translations.put("Oromucosal solution for gargle", "Раствор для полоскания рта и горла");
        translations.put("Oromucosal solution", "Раствор для приема в полость рта");
        translations.put("Oromucosal suspension", "Суспензия для приема в полость рта");
        translations.put("Oromucosal drops", "Капли для приема в полость рта");
        translations.put("Oromucosal spray", "Спрей для приема в полость рта");
        translations.put("Sublingual spray", "Сублингвальный спрей");
        translations.put("Gingival solution", "Раствор для десен");
        translations.put("Oromucosal gel", "Гель для слизистой оболочки рта");
        translations.put("Oromucosal paste", "Паста для слизистой оболочки рта");
        translations.put("Gingival gel", "Гель для десен");
        translations.put("Gingival paste", "Паста для десен");
        translations.put("Sublingual tablet", "Сублингвальная таблетка");
        translations.put("Buccal tablet", "Буккальная таблетка");
        translations.put("Prolonged-release muco-adhesive buccal tablet (dose form)", "Таблетка для буккального применения с мукоадгезивным эффектом, ");
        translations.put("Dental gel", "Стоматологический гель");
        translations.put("Dental stick", "Стоматологическая палочка");
        translations.put("Prolonged-release dental insert (dose form)", "Стоматологический препарат ");
        translations.put("Dental powder", "Стоматологический порошок");
        translations.put("Dental solution", "Стоматологический раствор");
        translations.put("Dental suspension", "Стоматологическая суспензия");
        translations.put("Dental emulsion", "Стоматологическая эмульсия");
        translations.put("Cutaneous paste", "Паста для наружного применения");
        translations.put("Cutaneous foam", "Пена для наружного применения");
        translations.put("Cutaneous spray", "Спрей для наружного применения");
        translations.put("Cutaneous solution spray", "Раствор в спрее для наружного применения");
        translations.put("Cutaneous solution", "Раствор для наружного применения");
        translations.put("Cutaneous suspension", "Суспензия для наружного применения");
        translations.put("Cutaneous emulsion", "Эмульсия для наружного применения");
        translations.put("Cutaneous powder", "Порошок для наружного применения");
        translations.put("Solution for iontophoresis", "Раствор для ионтофореза");
        translations.put("Prolonged-release transdermal patch (dose form)", "Трансдермальный пластырь ");
        translations.put("Cutaneous stick", "Палочка для наружного применения");
        translations.put("Cutaneous sponge", "Губка для наружного применения");
        translations.put("Eye cream", "Крем для глаз");
        translations.put("Eye gel", "Гель для глаз");
        translations.put("Eye ointment", "Мазь для глаз");
        translations.put("Eye drops", "Капли для глаз");
        translations.put("Eye drops solution", "Раствор капель для глаз");
        translations.put("Prolonged-release eye drops", "Продленно-действующие капли для глаз");
        translations.put("Prolonged-release ophthalmic insert (dose form)", "Офтальмологический продленно-действующий препарат в виде вкладыша");
        translations.put("Ear cream", "Крем для ушей");
        translations.put("Ear gel", "Гель для ушей");
        translations.put("Ear ointment", "Мазь для ушей");
        translations.put("Ear drops", "Капли для ушей");
        translations.put("Ear drops solution", "Раствор капель для ушей");
        translations.put("Ear drops emulsion", "Эмульсия капель для ушей");
        translations.put("Ear powder", "Порошок для ушей");
        translations.put("Ear spray", "Спрей для ушей");
        translations.put("Ear spray solution", "Раствор спрея для ушей");
        translations.put("Ear spray suspension", "Суспензия спрея для ушей");
        translations.put("Ear spray emulsion", "Эмульсия спрея для ушей");
        translations.put("Ear tampon", "Тампон для ушей");
        translations.put("Ear stick", "Палочка для ушей");
        translations.put("Nasal cream", "Крем для носа");
        translations.put("Nasal gel", "Гель для носа");
        translations.put("Nasal ointment", "Мазь для носа");
        translations.put("Nasal drops", "Капли для носа");
        translations.put("Nasal drops solution", "Раствор капель для носа");
        translations.put("Nasal drops suspension", "Суспензия капель для носа");
        translations.put("Nasal drops emulsion", "Эмульсия капель для носа");
        translations.put("Nasal powder", "Порошок для носа");
        translations.put("Nasal spray", "Спрей для носа");
        translations.put("Nasal solution spray", "Спрей-раствор для носа");
        translations.put("Nasal suspension spray", "Суспензия спрея для носа");
        translations.put("Nasal emulsion spray", "Эмульсия спрея для носа");
        translations.put("Nasal stick", "Палочка для носа");
        translations.put("Conventional release ear or eye or nose drops (dose form)", "Капли ушные или глазные или назальные");
        translations.put("Conventional release ear or eye or nose ointment", "Мазь ушная или глазная или назальная ");
        translations.put("Vaginal cream", "Вагинальный крем");
        translations.put("Vaginal gel", "Вагинальный гель");
        translations.put("Vaginal ointment", "Вагинальная мазь");
        translations.put("Vaginal foam", "Вагинальная пена");
        translations.put("Vaginal solution", "Вагинальный раствор");
        translations.put("Vaginal suspension", "Вагинальная суспензия");
        translations.put("Vaginal emulsion", "Вагинальная эмульсия");
        translations.put("Tablet for vaginal solution", "Таблетка для вагинального раствора");
        translations.put("Vaginal capsule", "Вагинальная капсула");
        translations.put("Hard vaginal capsule", "Вагинальная твердая капсула");
        translations.put("Soft vaginal capsule", "Вагинальная мягкая капсула");
        translations.put("Vaginal tablet", "Вагинальная таблетка");
        translations.put("Effervescent vaginal tablet", "Вагинальная шипучая таблетка");
        translations.put("Rectal cream", "Ректальный крем");
        translations.put("Rectal gel", "Ректальный гель");
        translations.put("Rectal ointment", "Ректальная мазь");
        translations.put("Rectal foam", "Ректальная пена");
        translations.put("Rectal solution", "Ректальный раствор");
        translations.put("Rectal suspension", "Ректальная суспензия");
        translations.put("Rectal emulsion", "Ректальная эмульсия");
        translations.put("Powder for rectal suspension", "Ректальный порошок для суспензии");
        translations.put("Tablet for rectal solution", "Ректальная растворимая таблетка");
        translations.put("Tablet for rectal suspension", "Ректальная таблетка для суспензии");
        translations.put("Rectal capsule", "Ректальная капсула");
        translations.put("Rectal tampon", "Ректальный тампон");
        translations.put("Conventional release solution for nebulizer (dose form)", "Раствор для ингаляции для небулайзера");
        translations.put("Conventional release suspension for nebulizer (dose form)", "Суспензия для ингаляции для небулайзера");
        translations.put("Powder for nebulizer suspension", "Порошок для суспензии для небулайзера");
        translations.put("Powder for nebulizer solution", "Порошок для раствора для небулайзера");
        translations.put("Conventional release emulsion for nebulizer (dose form)", "Эмульсия для ингаляции для небулайзера");
        translations.put("Pressurized solution for inhalation", "Раствор под давлением для ингаляции");
        translations.put("Pressurized suspension for inhalation", "Суспензия под давлением для ингаляции");
        translations.put("Pressurized emulsion for inhalation", "Эмульсия под давлением для ингаляции");
        translations.put("Powder for inhalation", "Порошок для ингаляции");
        translations.put("Gas for inhalation", "Газ для ингаляции");
        translations.put("Solution for injection", "Раствор для инъекций");
        translations.put("Suspension for injection", "Суспензия для инъекций");
        translations.put("Emulsion for injection", "Эмульсия для инъекций");
        translations.put("Powder for solution for injection", "Порошок для приготовления раствора для инъекций");
        translations.put("Powder for suspension for injection", "Порошок для приготовления суспензии для инъекций");
        translations.put("Solution for infusion", "Раствор для внутривенного введения");
        translations.put("Intravesical solution", "Раствор для внутрипузырного введения");
        translations.put("Urethral gel", "Уретральный гель");
        translations.put("Urethral stick", "Уретральная палочка");
        translations.put("Conventional release solution for endotracheopulmonary instillation", "Раствор для эндотрахеопульмонального вливания");
        translations.put("Conventional release suspension for endotracheopulmonary instillation (dose form)", "Суспензия для эндотрахеопульмонального вливания");
        translations.put("Endocervical gel", "Гель для эндоцервикального применения");
        translations.put("Parenteral dose form (dose form)", "Дозировочная форма для парентерального применения");
        translations.put("Rectal dose form (dose form)", "Дозировочная форма для ректального применения");
        translations.put("Nasal dose form (dose form)", "Дозировочная форма для назального применения");
        translations.put("Vaginal dose form (dose form)", "Дозировочная форма для вагинального применения");
        translations.put("Oral elixir", "Оральный эликсир");
        translations.put("Nasal emulsion", "Назальная эмульсия");
        translations.put("Rectal powder", "Ректальный порошок");
        translations.put("Conventional release oral coated pellets capsule", "Обыкновенная капсула с пеллетом для приема внутрь");
        translations.put("Prolonged-release film-coated oral tablet (dose form)", "Таблетка для приема внутрь с пленочным покрытием");
        translations.put("Lyophilized powder for prolonged-release suspension for injection (dose form)", "Лиофилизированный порошок для суспензии для инъекций с продолжительным высвобождением");
        translations.put("Oral granules", "Оральные гранулы");
        translations.put("Vaginal powder", "Вагинальный порошок");
        translations.put("Cutaneous oil", "Масло для наружного применения");
        translations.put("Vaginal insert", "Вагинальная вставка");
        translations.put("Conventional release ear or eye drops", "Капли для ушей или глаз ");
        translations.put("Solution for inhalation", "Раствор для ингаляции");
        translations.put("Oral capsule", "Капсула для приема внутрь");
        translations.put("Eye suspension", "Суспензия для глаз");
        translations.put("Gastro-resistant oral pellets capsule (dose form)", "Капсула с гастрорезистентными пеллетс для приема внутрь");
        translations.put("Prolonged-release suspension for injection", "Суспензия для инъекций с продолжительным высвобождением");
        translations.put("Ear drops suspension", "Суспензия капель для ушей");
        translations.put("Ear emulsion", "Эмульсия для ушей");
        translations.put("Rectal suppository", "Ректальная суппозитория");
        translations.put("Oral tablet", "Таблетка для приема внутрь");
        translations.put("Emulsion for inhalation", "Эмульсия для ингаляции");
        translations.put("Gastro-resistant and prolonged-release oral tablet", "Таблетка для перорального приема, с защитой от воздействия желудочного сока и удлиненным высвобождением");
        translations.put("Suspension for inhalation", "Суспензия для ингаляции");
        translations.put("Prolonged-release oral coated capsule", "Оболоченная капсула  для перорального приема");
        translations.put("Powder for cutaneous solution", "Порошок для раствора на коже");
        translations.put("Tablet for oral suspension", "Таблетка для пероральной суспензии");
        translations.put("Ear suspension", "Суспензия для ушей");
        translations.put("Powder for inhalation solution", "Порошок для раствора для ингаляции");
        translations.put("Conventional release ear or eye ointment (dose form)", "Обычный препарат для наружного применения на ухо или глаз");
        translations.put("Granules for extended-release oral suspension", "Гранулы  для пероральной суспензии");
        translations.put("Gastro-resistant oral particles tablet (dose form)", "Таблетка с гастрорезистентными частицами");
        translations.put("Prolonged-release buccal tablet", "Буккальная таблетка ");
        translations.put("Cutaneous cream", "Крем для наружного применения");
        translations.put("Lyophilized powder for conventional release solution for injection (dose form)", "Лиофилизированный порошок для обычного раствора для инъекций");
        translations.put("Tablet for oral solution", "Таблетка для перорального раствора");
        translations.put("Ear solution", "Раствор для ушей");
        translations.put("Gastro-resistant and prolonged-release oral capsule (dose form)", "Капсула для перорального приема с гастрорезистентностью и удлиненным высвобождением");
        translations.put("Conventional release solution for intraperitoneal injection (dose form)", "Обычный раствор для интраперитонеального введения");
        translations.put("Powder for ophthalmic solution", "Порошок для офтальмического раствора");
        translations.put("Tablet for cutaneous solution", "Таблетка для раствора для наружного применения");
        translations.put("Powder for prolonged-release suspension for injection (dose form)", "Порошок  суспензии для инъекций");
        translations.put("Nasal solution", "Назальный препарат");
        translations.put("Extended-release oral suspension", "Продленно-высвобождающаяся оральная суспензия");
        translations.put("Vaginal sponge", "Вагинальная губка");
        translations.put("Cutaneous ointment", "Наружный мазь");
        translations.put("Rectal spray", "Ректальный спрей");
        translations.put("Vaginal spray", "Вагинальный спрей");
        translations.put("Conventional release oral coated capsule (dose form)", "Обычная оральная покрытая капсула");
        translations.put("Intrauterine dose form", "Маточная дозированная форма");
        translations.put("Buccal film", "Буккальная пленка");
        translations.put("Orodispersible film", "Ородисперсируемая пленка");
        translations.put("Orodispersible tablet", "Ородисперсируемая таблетка");
        translations.put("Ophthalmic strip", "Глазная полоска");
        translations.put("Rectal suspension spray", "Ректальный суспензионный спрей");
        translations.put("Rectal solution spray", "Ректальный растворимый спрей");
        translations.put("Vaginal suspension spray", "Вагинальный суспензионный спрей");
        translations.put("Vaginal solution spray", "Вагинальный растворимый спрей");
        translations.put("Conventional release vaginal tampon (dose form)", "Обычный вагинальный тампон");
        translations.put("Urethral dose form (dose form)", "Уретральная дозированная форма");
        translations.put("Intravesical dose form (dose form)", "Межпузырная дозированная форма");
        translations.put("Cutaneous dose form", "Наружная дозированная форма");
        translations.put("Oromucosal dose form (dose form)", "Оромукальная дозированная форма");
        translations.put("Gingival dose form (dose form)", "Десневая дозированная форма");
        translations.put("Transdermal dose form (dose form)", "Трансдермальная форма дозирования");
        translations.put("Powder for rectal solution", "Порошок для ректального раствора");
        translations.put("Eye drops emulsion", "Эмульсия для глазных капель");
        translations.put("Delayed-release granules for oral suspension", "Отложенного действия гранулы для пероральной суспензии");
        translations.put("Oromucosal spray solution", "Ротовой аэрозольный спрей раствор");
        translations.put("Conventional release suspension for oromucosal spray", "Обыкновенная суспензия для ротового спрея");
        translations.put("Powder for intravesical suspension", "Порошок для межпузырной суспензии");
        translations.put("Conventional release eye emulsion", "Обыкновенная эмульсия для глаз");
        translations.put("Conventional release cutaneous lotion (dose form)", "Обыкновенный лосьон для наружного применения");
        translations.put("Intraocular dose form", "Внутриглазная форма дозирования");
        translations.put("Conventional release cutaneous tape", "Обыкновенная наружная лента");
        translations.put("Conventional release transdermal ointment (dose form)", "Обыкновенная наружная мазь");
        translations.put("Granules for conventional release oromucosal solution (dose form)", "Гранулы для конвенциональной ротовой суспензии");
        translations.put("Conventional release solution for sublingual spray", "Обыкновенный раствор для подъязычного спрея");
        translations.put("Conventional release dental paste", "Обыкновенная зубная паста");
        translations.put("Conventional release gel for injection (dose form)", "Обыкновенный гель для инъекций");
        translations.put("Intrauterine solution", "Внутриматочный раствор");
        translations.put("Intrauterine suspension", "Внутриматочная суспензия");
        translations.put("Prolonged-release transdermal film", "Длительного действия трансдермальная пленка");
        translations.put("Gastro-resistant oral suspension", "Желудочнокишечно-стойкая пероральная суспензия");
        translations.put("Powder for conventional release oromucosal gel", "Порошок для обыкновенного ротового геля");
        translations.put("Conventional release buccal spray", "Обыкновенный буккальный спрей");
        translations.put("Prolonged-release subcutaneous implant", "Продленно-действующий подкожный имплантат");
        translations.put("Conventional release transdermal foam", "Трансдермальная пена ");
        translations.put("Enteral dose form", "Дозируемая форма для приема внутрь");
        translations.put("Conventional release nasal paste", "Назальная паста ");
        translations.put("Conventional release transdermal cream (dose form)", "Трансдермальный крем  (дозируемая форма)");
        translations.put("Gingival ointment", "Десенсибилизирующий гель");
        translations.put("Conventional release cutaneous patch (dose form)", "Трансдермальный пластырь  (дозируемая форма)");
        translations.put("Prolonged-release cutaneous patch (dose form)", "Продленно-действующий трансдермальный пластырь (дозируемая форма)");
        translations.put("Conventional release buccal lozenge (dose form)", "Пресованный таблетки для рассасывания в полости рта  (дозируемая форма)");
        translations.put("Oromucosal lozenge", "Таблетки для рассасывания в полости рта");
        translations.put("Sublingual dose form (dose form)", "Дозируемая форма для применения подъязычно");
        translations.put("Dual delayed-release oral capsule (dose form)", "Оральная капсула с двойной задержкой высвобождения (дозируемая форма)");
        translations.put("Prolonged-release vaginal ring", "Продленно-действующее вагинальное кольцо");
        translations.put("Conventional release oromucosal pastille", "Оромукальная пастилка ");
        translations.put("Conventional release and prolonged-release oral tablet", "Оральная таблетка с обычным и продленным высвобождением");
        translations.put("Dental pellet", "Дентальные шарики");
        translations.put("Conventional release effervescent oral tablet (dose form)", "Шипучая оральная таблетка  (дозируемая форма)");
        translations.put("Conventional release effervescent oral tablet (dose form)", "Эффервесцентная таблетка для приема внутрь обычного отпуска");
        translations.put("Conventional release oropharyngeal foam (dose form)", "Орофарингеальная пена обычного отпуска");
        translations.put("Oropharyngeal solution", "Раствор для применения в полости рта и/или глотки");
        translations.put("Pulmonary dose form (dose form)", "Форма дозирования для легких");
        translations.put("Suspension for infusion", "Суспензия для внутривенного введения");
        translations.put("Conventional release transdermal gel (dose form)", "Трансдермальный гель обычного отпуска");
        translations.put("Transdermal spray", "Трансдермальный спрей");
        translations.put("Prolonged-release ocular implant", "Имплантат для глаз с продленным высвобождением");
        translations.put("Powder for conventional release solution for infusion (dose form)", "Порошок для раствора для внутривенного введения обычного отпуска");
        translations.put("Lyophilized powder for conventional release solution for infusion", "Лиофилизированный порошок для раствора для внутривенного введения обычного отпуска");
        translations.put("Gastro-resistant oral soft capsule", "Мягкая оболочка для препаратов с защитой от воздействия желудочно-кишечного сока");
        translations.put("Prolonged-release oral soft capsule (dose form)", "Мягкая оболочка с продленным высвобождением для приема внутрь");
        translations.put("Modified-release oral soft capsule", "Мягкая оболочка с измененным высвобождением для приема внутрь");
        translations.put("Powder for suspension for infusion", "Порошок для суспензии для внутривенного введения");
        translations.put("Conventional release solution for ear or eye drops (dose form)", "Раствор для ушей или глаз обычного отпуска");
        translations.put("Ear or eye or nose drops solution", "Раствор для ушей, глаз или носа");
        translations.put("Ocular or otic dose form", "Форма дозирования для глаз или ушей");
        translations.put("Nasal or ocular or otic dose form", "Форма для дозировки носовых или глазных или ушных лекарственных средств");
        translations.put("Emulsion for infusion", "Эмульсия для инфузии");
        translations.put("Gastro-resistant and prolonged-release oral granules (dose form)", "Гастрорезистентные и длительно действующие гранулы для приема внутрь");
        translations.put("Powder for conventional release suspension for inhalation (dose form)", "Порошок суспензии для ингаляции");
        translations.put("Oropharyngeal dose form (dose form)", "Форма для дозировки для приема через рот или глотку");
        translations.put("Vaginal pessary", "Вагинальная свеча");
        translations.put("Subcutaneous dose form", "Подкожная форма для дозировки");
        translations.put("Effervescent powder for conventional release oral solution", "Шипучий порошок перорального раствора");
        translations.put("Effervescent powder for oral suspension", "Шипучий порошок для пероральной суспензии");
        translations.put("Endotracheopulmonary dose form", "Форма для дозировки для эндотрахеопульмонального введения");
        translations.put("Buccal dose form", "Буккальная форма для дозировки");
        translations.put("Prolonged-release vaginal pessary (dose form)", "Длительно действующая вагинальная свеча");
        translations.put("Conventional release foam for injection", "Пенная форма для инъекций");
        translations.put("Conventional release oral ointment (dose form)", "Оральное мазь");
        translations.put("Oral spray", "Пероральный спрей");
        translations.put("Prolonged-release intrauterine drug delivery system (dose form)", "Длительно действующая внутриутробная система доставки лекарственных средств");
        translations.put("Conventional release solution for irrigation", "Раствор для ирригации");
        translations.put("Conventional release solution for ocular irrigation (dose form)", "Раствор для орошения глаз");
        translations.put("Conventional release cutaneous shampoo", "Шампунь для кожи");
        translations.put("Prolonged-release intralesional implant", "Имплантат местного действия с продленным высвобождением");
        translations.put("Conventional release intraarticular implant (dose form)", "Интраартикулярный имплантат (дозировочная форма)");
        translations.put("Conventional release chewable capsule (dose form)", "Жевательная капсула (дозировочная форма)");
        translations.put("Conventional release oral pellets in capsule", "Оральные гранулы в капсуле");
        translations.put("Powder for conventional release oral or rectal suspension", "Порошок для оральной или ректальной суспензии ");
        translations.put("Conventional release gas for insufflation", "Газ для надувания");
        translations.put("Cutaneous emulsion for bathing", "Эмульсия для купания");
        translations.put("Film-coated oral tablet", "Оральная таблетка с пленкой");
        translations.put("Conventional release cutaneous oil for bathing", "Масло для кожи для купания");
        translations.put("Solution for infusion and/or injection", "Раствор для внутривенного и/или внутримышечного введения");
        translations.put("Powder for conventional release solution for infusion and/or injection (dose form)", "Порошок для раствора для внутривенного и/или внутримышечного введения (дозировочная форма)");
        translations.put("Conventional release suspension for ear or nose drops (dose form)", "Суспензия для ушных или назальных капель (дозировочная форма)");
        translations.put("Conventional release solution for intravesical or urethral irrigation", "Раствор для интравезикального или уретрального промывания ");
        translations.put("Oral or rectal solution", "Оральный или ректальный раствор");
        translations.put("Granules for oral or rectal suspension", "Гранулы для приема внутрь или ректальной суспензии");
        translations.put("Conventional release emulsion for infusion and/or injection", "Эмульсия для инфузии и/или инъекции");
        translations.put("Delayed-release oral hard capsule", "Капсула с отложенным высвобождением для приема внутрь");
        translations.put("Extended-release oral hard capsule", "Капсула с продленным высвобождением для приема внутрь");
        translations.put("Modified-release oral hard capsule", "Капсула с модифицированным высвобождением для приема внутрь");
        translations.put("Conventional release hard oral capsule", "Твердая капсула для приема внутрь");
        translations.put("Conventional release soft oral capsule", "Мягкая капсула для приема внутрь");
        translations.put("Oromucosal ointment", "Мазь оральная для слизистой");
        translations.put("Conventional release oromucosal cream", "Крем оральный для слизистой");
        translations.put("Conventional release solution for ear or nose drops", "Раствор для ушных или назальных капель");
        translations.put("Powder for conventional release vaginal solution (dose form)", "Порошок для вагинального раствора ");
        translations.put("Conventional release transdermal solution (dose form)", "Трансдермальный раствор ");
        translations.put("Conventional release solution for transdermal spray (dose form)", "Раствор для трансдермального спрея ");
        translations.put("Oromucosal spray emulsion", "Эмульсия для орального слизистого спрея");
        translations.put("Conventional release emulsion for sublingual spray (dose form)", "Эмульсия  для сублингвального спрея");
        translations.put("Powder for solution for iontophoresis", "Порошок для раствора для ионтофореза");
        translations.put("Conventional release emulsion for cutaneous spray (dose form)", "Эмульсия  для кожного спрея");
        translations.put("Conventional release ointment for cutaneous spray (dose form)", "Мазь для кожного распыления");
        translations.put("Dispersion for infusion", "Дисперсия для инфузии");
        translations.put("Conventional release dispersion for injection", "Диспергирование для инъекции");
        translations.put("Extended-release dispersion for injection", "Дисперсия с продленным высвобождением для инъекции");
        translations.put("Tablet for conventional release oromucosal solution for gargle", "Таблетка для обыкновенного отпуска оромуцинского раствора для полоскания");
        translations.put("Gas for conventional release dispersion for infusion (dose form)", "Газ для обыкновенного отпуска диспергирования для инфузии");
        translations.put("Gas for conventional release dispersion for injection", "Газ для обыкновенного отпуска диспергирования для инъекции");
        translations.put("Powder for conventional release dispersion for infusion", "Порошок для обыкновенного отпуска диспергирования для инфузии");
        translations.put("Powder for conventional release oromucosal solution for gargle", "Порошок для обыкновенного отпуска оромуцинского раствора для полоскания");
        translations.put("Powder for conventional release oromucosal solution for mouthwash (dose form)", "Порошок для обыкновенного отпуска оромуцинского раствора для полоскания рта");
        translations.put("Oromucosal compressed lozenge", "Оромуциновый компрессированный леденец");
        translations.put("Conventional release periodontal gel (dose form)", "Обыкновенный отпуск периодонтального геля");
        translations.put("Conventional release periodontal powder (dose form)", "Обыкновенный отпуск периодонтального порошка");
        translations.put("Conventional release periodontal insert", "Обыкновенное отпускное периодонтальное введение");
        translations.put("Conventional release cutaneous lacquer", "Обыкновенное отпускное кожное лаковое покрытие");
        translations.put("Powder for dispersion for injection", "Порошок для дисперсии для инъекции");
        translations.put("Powder for solution for endotracheopulmonary instillation", "Порошок для раствора для эндотрахеопульмональной инстилляции");
        translations.put("Powder for conventional release suspension for endotracheopulmonary instillation", "Порошок для обычного отпуска суспензии для эндотрахеопульмональной инстилляции");
        translations.put("Conventional release cryogenic gas for inhalation (dose form)", "Обыкновенный отпуск криогенного газа для ингаляции (форма дозирования)");
        translations.put("Conventional release liquified gas for inhalation", "Обыкновенный отпуск сжиженного газа для ингаляции");
        translations.put("Conventional release compressed gas for inhalation", "Обыкновенный отпуск сжатого газа для ингаляции");
        translations.put("Conventional release oral effervescent powder (dose form)", "Обыкновенный отпуск эффервесцентного порошка для приема внутрь (форма дозирования)");
        translations.put("Conventional release cutaneous poultice (dose form)", "Обыкновенный отпуск кожного настоя (форма дозирования)");
        translations.put("Conventional release sublingual lyophilisate (dose form)", "Обыкновенный отпуск сублингвального лиофилизата (форма дозирования)");
        translations.put("Conventional release effervescent granules for oral suspension (dose form)", "Обыкновенный отпуск эффервесцентных гранул для приема внутрь в виде суспензии (форма дозирования)");
        translations.put("Conventional release sublingual powder (dose form)", "Обыкновенный отпуск сублингвального порошка (форма дозирования)");
        translations.put("Conventional release sublingual film (dose form)", "Обыкновенный отпуск сублингвальной пленки (форма дозирования)");
        translations.put("Conventional release coated oral tablet (dose form)", "Обыкновенный отпуск покрытых оральных таблеток (форма дозирования)");
        translations.put("Coated oral granules", "Покрытые оральные гранулы");
        translations.put("Prolonged-release periodontal insert", "Длительно действующее периодонтальное введение");
        translations.put("Cutaneous collodion", "Кожный коллодий");
        translations.put("Conventional release dental cement (dose form)", "Обыкновенный дентальный цемент (дозировочная форма)");
        translations.put("Conventional release powder for dental cement", "Обыкновенный порошок для дентального цемента");
        translations.put("Urethral ointment", "Уретральная мазь");
        translations.put("Oromucosal film", "Оромукоцильная пленка");
        translations.put("Powder for conventional release suspension for oral drops", "Порошок для конвенциональной суспензии для приема внутрь");
        translations.put("Granules for solution for oral drops", "Гранулы для раствора для приема внутрь");
        translations.put("Solution for peritoneal dialysis", "Раствор для перитонеального диализа");
        translations.put("Conventional release solution for hemodialysis", "Обыкновенный раствор для гемодиализа");
        translations.put("Extracorporeal dose form", "Экстракорпоральная форма дозирования");
        translations.put("Conventional release solution for hemofiltration (dose form)", "Обыкновенный раствор для гемофильтрации");
        translations.put("Conventional release solution for hemodiafiltration (dose form)", "Обыкновенный раствор для гемодиафильтрации");
        translations.put("Conventional release solution for hemodiafiltration or hemodialysis (dose form)", "Обыкновенный раствор для гемодиафильтрации или гемодиализа");
        translations.put("Conventional release oromucosal solution for gargle or mouthwash (dose form)", "Обыкновенный оромукоцильный раствор для полоскания или ополаскивания рта");
        translations.put("Emulsion for vapor inhalation", "Эмульсия для ингаляции пара");
        translations.put("Conventional release powder for vapor inhalation (dose form)", "Обыкновенный порошок для ингаляции пара");
        translations.put("Conventional release ointment for vapor inhalation", "Обыкновенная мазь для ингаляции пара");
        translations.put("Capsule for vapor inhalation", "Капсула для ингаляции пара");
        translations.put("Tablet for vapor inhalation", "Таблетка для ингаляции пара");
        translations.put("Solution for vapor inhalation", "Раствор для ингаляции пара");
        translations.put("Prolonged-release vaginal delivery system (dose form)", "Продолжительно действующая вагинальная система доставки");
        translations.put("Prolonged-release transdermal delivery system (dose form)", "Продолжительно действующая трансдермальная система доставки");
        translations.put("Conventional release solution for cardioplegia", "Обычный раствор для кардиоплегии");
        translations.put("Powder for conventional release intravesical solution (dose form)", "Порошок для обычного внутрипузырного раствора");
        translations.put("Intravesical suspension", "Внутрипузырная суспензия");
        translations.put("Pure liquid for vapor inhalation", "Чистая жидкость для ингаляции паров");
        translations.put("Conventional release cutaneous pure liquid (dose form)", "Обычный чистый жидкий препарат для наружного применения");
        translations.put("Oral pure liquid", "Чистая жидкость для приема внутрь");
        translations.put("Pure liquid for oral drops", "Чистая жидкость для пероральных капель");
        translations.put("Powder for conventional release solution for intraocular drops", "Порошок для обычного раствора для глазных капель");
        translations.put("Conventional release solution for intraocular drops (dose form)", "Обычный раствор для глазных капель");
        translations.put("Conventional release toothpaste (dose form)", "Обычная зубная паста");
        translations.put("Conventional release solution for cardioplegia or organ preservation (dose form)", "Обычный раствор для кардиоплегии или сохранения органов");
        translations.put("Impregnated material for conventional release ophthalmic application (dose form)", "Пропитанный материал для обычного глазного применения");
        translations.put("Prolonged release solution for injection (dose form)", "Продолжительно действующий раствор для инъекций");
        translations.put("Absorbent impregnated material for conventional release cutaneous application", "Впитывающий пропитанный материал для обычного наружного применения");
        translations.put("Conventional release dispersion for nebulizer", "Обычный дисперсный препарат для небулайзера");
        translations.put("Absorbent impregnated material for conventional release vapor inhalation", "Поглощающий пропитанный материал для обыкновенного отпуска парового ингалятора");
        translations.put("Porous impregnated material for conventional release vapor inhalation", "Пористый пропитанный материал для обыкновенного отпуска парового ингалятора");
        translations.put("Conventional release solution for dental cement (dose form)", "Обыкновенное растворение для зубного цемента");
        translations.put("Gas for conventional release dispersion for infusion or injection (dose form)", "Газ для обыкновенного растворения дисперсии для внутривенного или инъекционного введения");
        translations.put("Emulsion for infusion or injection", "Эмульсия для внутривенного или инъекционного введения");
        translations.put("Conventional release dispersion for infusion or injection (dose form)", "Обыкновенное растворение дисперсии для внутривенного или инъекционного введения");
        translations.put("Conventional release solution for infusion or injection (dose form)", "Обыкновенное растворение для внутривенного или инъекционного введения");
        translations.put("Powder for conventional release solution for infusion or injection (dose form)", "Порошок для обыкновенного растворения для внутривенного или инъекционного введения");
        translations.put("Conventional release solution for tissue adhesive", "Обыкновенное растворение для тканевого клея");
        translations.put("Conventional release powder for tissue adhesive", "Обыкновенный порошок для тканевого клея");
        translations.put("Conventional release impregnated material for tissue adhesive (dose form)", "Обыкновенный пропитанный материал для тканевого клея");
        translations.put("Conventional release dispersion for infusion and/or injection (dose form)", "Обыкновенное растворение дисперсии для внутривенного и/или инъекционного введения");
        translations.put("Gas for dispersion for infusion and/or injection", "Газ для дисперсии для внутривенного и/или инъекционного введения");
        translations.put("Powder for solution for tissue adhesive", "Порошок для растворения для тканевого клея");
        translations.put("Solution for solution for tissue adhesive", "Раствор для раствора тканевого клея");
        translations.put("Gastroenteral solution", "Раствор для гастроэнтерального применения");
        translations.put("Gastroenteral suspension", "Суспензия для гастроэнтерального применения");
        translations.put("Gastroenteral emulsion", "Эмульсия для гастроэнтерального применения");
        translations.put("Oral dose form", "Лекарственная форма для приема внутрь");
        translations.put("Dental dose form (dose form)", "Лекарственная форма для стоматологического применения");
        translations.put("Ocular dose form (dose form)", "Лекарственная форма для глазного применения");
        translations.put("Otic dose form (dose form)", "Лекарственная форма для ушного применения");
        translations.put("Cutaneous powder spray", "Порошковый спрей для наружного применения");
        translations.put("Cutaneous suspension spray", "Суспензионный спрей для наружного применения");
        translations.put("Gastroenteral dose form (dose form)", "Лекарственная форма для гастроэнтерального применения");
        translations.put("Endocervical dose form", "Лекарственная форма для вагинального применения");
        translations.put("Oral cream", "Крем для приема внутрь");
        translations.put("Lyophilized powder for conventional release suspension for injection (dose form)", "Лиофилизированный порошок для суспензии для инъекций");
        translations.put("Cutaneous gel", "Гель для наружного применения");
        translations.put("Ophthalmic solution", "Офтальмологический раствор");
        translations.put("Eye drops suspension", "Суспензия для глазных капель");
        translations.put("Nasal suspension", "Суспензия для назального применения");
        translations.put("Powder for ophthalmic suspension", "Порошок для офтальмологической суспензии");
        translations.put("Once", "Единоразово");
        translations.put("Periodically", "Периодически");
        translations.put("On demand", "По востребованию");
        translations.put("Titration method", "Тетрационный метод");
    }
}
